# Generated by Django 6.0.2 on 2026-02-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Подзаголовок')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Изображение')),
                ('link', models.CharField(max_length=500, verbose_name='Ссылка/WhatsApp')),
                ('button_text', models.CharField(max_length=50, verbose_name='Текст кнопки')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок статьи')),
                ('meta', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('image', models.ImageField(upload_to='blog/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='categories/')),
                ('url_name', models.CharField(max_length=100, verbose_name='Ссылка (напр. rings.html)')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='features/')),
                ('is_large', models.BooleanField(default=False, verbose_name='Большой блок?')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('stars', models.IntegerField(default=5, verbose_name='Кол-во звезд')),
            ],
        ),
    ]
